### ISSUE TITLE
Twitch Tags

### ISSUE THREAD

**Issue by kacollins** [techlahoma/broadcasting#12]
Add the step of selecting tags on Twitch to the streaming instructions, along with a list of suggested tags to use.

**Comment by Archyver** [comment]
Didn't even check the issues section of /broadcast. Fixed with pull request 16, following along with https://github.com/austinwk/2018_hacktoberfest_participants instructions. Thanks all

**Comment by kacollins** [comment]
Thanks for doing this! There is plenty more to do if you're interested. :)
