### ISSUE TITLE
Break team list into separate markdown files

### ISSUE THREAD

**Issue by kacollins** [techlahoma/broadcasting#46]
The team list is getting too long and needs to be broken into separate files: https://github.com/techlahoma/broadcasting/blob/master/Teams/teams.md

- [ ] Create a markdown file in the Teams folder for each team listed
- [ ] Move the contents for each team from teams.md into the team's markdown file
- [ ] Change the link in the top section of teams.md to point to the team's markdown file

**Comment by linuxuser07** [comment]
I can do this

**Comment by kacollins** [comment]
Thank you @linuxuser07!
