### ISSUE TITLE
Team Links

### ISSUE THREAD

**Issue by kacollins** [techlahoma/broadcasting#48]
- [ ] Change the links in the first section of https://github.com/techlahoma/broadcasting/blob/master/Teams/_Teams.md to point to the links in the following section headers.
- [ ] Remove the following section headers. 
- [ ] Remove the link from the first section header.

**Comment by gregsnewby** [comment]
@kacollins I can do this one!

**Comment by kacollins** [comment]
Great! It should be pretty straightforward, but I wasn't totally sure how to word the tasks to make them clear. If you have any questions about it, just ask!

**Comment by gregsnewby** [comment]
I think I got it. LMK!

**Comment by kacollins** [comment]
You did. Thank you!
