### ISSUE TITLE
Clock Instructions

### ISSUE THREAD

**Issue by kacollins** [techlahoma/broadcasting#7]
Add a markdown file with instructions for how to set the clock and timer

**Comment by kacollins** [comment]
![image](https://user-images.githubusercontent.com/15042297/46759256-8695f200-cc94-11e8-8753-dca94d516fd1.png)

**Comment by kacollins** [comment]
This will go in the `Presenting` folder and also needs to be in the table of contents in the readme.

**Comment by linuxuser07** [comment]
Ill take a shot a this one too

**Comment by kacollins** [comment]
Done in #19
